# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    windows:
#     imageName: 'vs2017-win2016'
      imageName: 'windows-2019'
#    mac:
#     imageName: 'macos-latest'

pool:
  vmImage: $(imageName)

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**/VeriSol.sln'

- task: DotNetCoreCLI@2
  displayName: 'Install VeriSol as dotnet cli tool'
  inputs:
    command: custom
    custom: 'tool'
    arguments: 'install --tool-path $(Build.SourcesDirectory)/Tools/ VeriSol --version 0.1.5-alpha --add-source $(Build.SourcesDirectory)/nupkg/'

- pwsh: |
   $(Build.SourcesDirectory)/Tools/VeriSol $(Build.SourcesDirectory)/Test/regressions/DAO-Sim-Buggy.sol Mallory /tryProof /tryRefutation:10 /printTransactionSequence
   cat boogie.txt
   cat corral.txt

   $(Build.SourcesDirectory)/Tools/VeriSol $(Build.SourcesDirectory)/Test/regressions/ERC20-simplified.sol ERC20 /tryProof /tryRefutation:10 /printTransactionSequence
   cat boogie.txt
  displayName: 'Run VeriSol on some examples'

- task: DotNetCoreCLI@2
  displayName: 'Install SolToBoogieTest as dotnet cli tool'
  inputs:
    command: custom
    custom: 'tool'
    arguments: 'install --tool-path $(Build.SourcesDirectory)/Tools/ SolToBoogieTest --version 0.1.5-alpha --add-source $(Build.SourcesDirectory)/nupkg/'

- pwsh: '$(Build.SourcesDirectory)/Tools/VeriSolRegressionRunner $(Build.SourcesDirectory)/Test/'
  displayName: 'Run regression tests'
